apiVersion: v1
kind: Service
metadata:
  name: {{ include "msgraph.fullname" . }}
  labels:
    {{- include "msgraph.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: http
      appProtocol: {{ ternary "https" "http" (eq .Values.transportSecurity.mode "tls") }}
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    {{- include "msgraph.selector" . | nindent 4 }}
